#!/usr/bin/env python3
"""Generate website/status.json from repo state (single source of truth).

Fields:
  spec       — latest Draft version mentioned in standard/CORE.md
  sdk        — version string from sdk/package.json
  sdkTests   — number of `test(` cases across sdk/test/*.test.mjs
  profiles   — number of runtime profiles in profiles/*.md
  conformance— "Passing", bound by the `verified` block (sha/date/run URL of
               the green CI run that wrote it); absent verified means the
               file was written outside CI and must not be served as proof

Usage:
  python3 scripts/gen_status.py --check   # exit 1 if website/status.json is stale
  python3 scripts/gen_status.py --write   # rewrite website/status.json

The website fetches status.json at runtime (website/script.js); unknown keys
are ignored, so adding fields is forward-compatible.
"""
from __future__ import annotations

import argparse
import datetime
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def detect_spec_version() -> str:
    """Current spec version: major.minor from the CORE.md header declaration,
    plus the highest patch number referenced for that major.minor across
    standard/*.md (roadmap mentions of future majors are ignored)."""
    core = open(os.path.join(ROOT, "standard", "CORE.md"), encoding="utf-8").read()
    head = re.search(r"\*\*Draft (\d+)\.(\d+)", core)
    if not head:
        return "unknown"
    major, minor = head.group(1), head.group(2)
    patches = [0]
    for path in glob.glob(os.path.join(ROOT, "standard", "*.md")):
        text = open(path, encoding="utf-8").read()
        for m in re.finditer(rf"Draft {re.escape(major)}\.{re.escape(minor)}\.(\d+)", text):
            patches.append(int(m.group(1)))
    patch = max(patches)
    return f"Draft {major}.{minor}" + (f".{patch}" if patch else "")


def detect_sdk_version() -> str:
    pkg = json.load(open(os.path.join(ROOT, "sdk", "package.json"), encoding="utf-8"))
    v = pkg.get("version", "0.0.0")
    return f"v{v}"


def count_sdk_tests() -> int:
    total = 0
    for path in glob.glob(os.path.join(ROOT, "sdk", "test", "*.test.mjs")):
        src = open(path, encoding="utf-8").read()
        total += len(re.findall(r"^\s*(?:test|it)\s*\(", src, re.M))
    return total


def count_profiles() -> int:
    return len(glob.glob(os.path.join(ROOT, "profiles", "*.md")))


def build_status() -> dict:
    status = {
        "updated": datetime.date.today().isoformat(),
        "source": "generated by CI from repo state (scripts/gen_status.py)",
        "spec": detect_spec_version(),
        "sdk": detect_sdk_version(),
        "sdkTests": count_sdk_tests(),
        "profiles": count_profiles(),
        "conformance": "Passing",
    }
    # "Passing" is only ever written by a green CI run (status-sync needs the
    # five check jobs). The verified block binds that claim to the exact run
    # that produced it, so the site can never show a stale Passing as current.
    run_id = os.environ.get("GITHUB_RUN_ID")
    if run_id:
        server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
        repo = os.environ.get("GITHUB_REPOSITORY", "roy-tong/AgentMeasure")
        status["verified"] = {
            "sha": os.environ.get("GITHUB_SHA", "")[:7],
            "at": datetime.datetime.now(datetime.timezone.utc).date().isoformat(),
            "run": f"{server}/{repo}/actions/runs/{run_id}",
        }
    else:
        status["verified"] = None
    return status


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if stale")
    ap.add_argument("--write", action="store_true", help="rewrite website/status.json")
    args = ap.parse_args()

    status = build_status()
    path = os.path.join(ROOT, "website", "status.json")

    if args.write:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(status, fh, indent=2)
            fh.write("\n")
        print("wrote website/status.json:", json.dumps(status))
        return 0

    current = json.load(open(path, encoding="utf-8")) if os.path.exists(path) else {}
    # verified is CI-run provenance (absent locally); updated is a date.
    # --check only guards the stable repo-state fields.
    volatile = {"updated", "verified"}
    live = {k: v for k, v in current.items() if k not in volatile}
    fresh = {k: v for k, v in status.items() if k not in volatile}
    if live != fresh:
        print("website/status.json is stale:")
        for k in sorted(set(live) | set(fresh)):
            if live.get(k) != fresh.get(k):
                print(f"  {k}: {live.get(k)!r} -> {fresh.get(k)!r}")
        return 1 if args.check else 0
    print("website/status.json up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
